package com.chimallidigital.solucionint.domain.model.Settings

data class SettingsTabataTimerModel(
    var preparacion_horas: Int,
    var preparacion_minutos: Int,
    var preparacion_segundos: Int,
    var ejercicios_horas: Int,
    var ejercicios_minutos: Int,
    var ejercicios_segundos: Int,
    var descanso_horas: Int,
    var descanso_minutos: Int,
    var descanso_segundos: Int,
    var descanso_entre_conjuntos_horas: Int,
    var descanso_entre_conjuntos_minutos: Int,
    var descanso_entre_conjuntos_segundos: Int,
    var count_ciclos: Int,
    var count_conjuntos: Int,
    var tiempoTotal: Int,
    var preparacion_tiempo: Int,
    var ejercicio_tiempo: Int,
    var descanso_tiempo: Int,
    var descanso_entre_tiempo: Int,
    var track_ejercicio: Int,
    var track_descanso: Int,
    var track_descanso_entre: Int,
    var vibration_state_ejercicio: Boolean,
    var vibration_state_descanso: Boolean,
    var vibration_state_descanso_entre: Boolean,
    var positionDescansoHoras: Int,
    var positionDescansoMinutos: Int,
    var positionDescansoSegundos: Int,
    var positionDescansoEntreHoras: Int,
    var positionDescansoEntreMinutos: Int,
    var positionDescansoEntreSegundos: Int,
    var positionEjercicioHoras:Int,
    var positionEjercicioMinutos:Int,
    var positionEjercicioSegundos:Int,
    var positionPreparacionHoras: Int,
    var positionPreparacionMinutos: Int,
    var positionPreparacionSegundos: Int,
    var positionTrackDescanso:Int,
    var positionTrackDescansoEntre: Int,
    var positionTrackEjercicio: Int
)