package com.chimallidigital.solucionint.domain

class StringsCollection(val string: String) {
    companion object{
        val URL = "URL"
        val ITEMS_LIST="ITEMS_LIST"
        const val SONIDO_TEMPORIZADOR= "sonido_temporizador"
        const val VIBRACION_TEMPORIZADOR= "vibracion_temporizador"
        const val TRACK_TEMPORIZADOR="track_temporizador"

        const val TT_TIEMPO_TOTAL="tt_tiempo_total"
        const val TT_PREPARACION_HORAS="tt_preparacion_horas"
        const val TT_PREPARACION_MINUTOS="tt_preparacion_minutos"
        const val TT_PREPARACION_SEGUNDOS="tt_preparacion_segundos"
        const val TT_EJERCICIO_HORAS="tt_ejercicio_horas"
        const val TT_EJERCICIO_MINUTOS="tt_ejercicio_minutos"
        const val TT_EJERCICIO_SEGUNDOS="tt_ejercicio_segundos"
        const val TT_DESCANSO_HORAS="tt_descanso_horas"
        const val TT_DESCANSO_MINUTOS="tt_descanso_minutos"
        const val TT_DESCANSO_SEGUNDOS="tt_descanso_segundos"
        const val TT_DESCANSO_ENTRE_CONJUNTOS_HORAS="tt_descanso_entre_conjuntos_horas"
        const val TT_DESCANSO_ENTRE_CONJUNTOS_MINUTOS="tt_descanso_entre_conjuntos_minutos"
        const val TT_DESCANSO_ENTRE_CONJUNTOS_SEGUNDOS="tt_descanso_entre_conjuntos_segundos"
        const val TT_COUNT_CICLOS="tt_count_ciclos"
        const val TT_COUNT_CONJUNTOS="tt_count_conjuntos"
        const val TT_TIEMPOTOTAL="tt_tiempototal"
        const val TT_PREPARACION_TIEMPO="tt_preparacion_tiempo"
        const val TT_EJERCICIO_TIEMPO="tt_ejercicio_tiempo"
        const val TT_DESCANSO_TIEMPO="tt_descanso_tiempo"
        const val TT_DESCANSO_ENTRE_TIEMPO="tt_descanso_entre_tiempo"
        const val TT_TRACK_EJERCICIO="tt_track_ejercicio"
        const val TT_TRACK_DESCANSO="tt_track_descanso"
        const val TT_TRACK_DESCANSO_ENTRE="tt_track_descanso_entre"
        const val TT_VIBRATION_STATE_EJERCICIO="tt_vibration_state_ejercicio"
        const val TT_VIBRATION_STATE_DESCANSO="tt_vibration_state_descanso"
        const val TT_VIBRATION_STATE_DESCANSO_ENTRE="tt_vibration_state_descanso_entre"
        const val TT_POSITION_DESCANSO_HORAS="tt_position_descanso_horas"
        const val TT_POSITION_DESCANSO_MINUTOS="tt_position_descanso_minutos"
        const val TT_POSITION_DESCANSO_SEGUNDOS="tt_position_descanso_segundos"
        const val TT_POSITION_DESCANSO_ENTRE_HORAS="tt_position_descanso_entre_horas"
        const val TT_POSITION_DESCANSO_ENTRE_MINUTOS="tt_position_descanso_entre_minutos"
        const val TT_POSITION_DESCANSO_ENTRE_SEGUNDOS="tt_position_descanso_entre_segundos"
        const val TT_POSITION_EJERCICIO_HORAS="tt_position_ejercicio_horas"
        const val TT_POSITION_EJERCICIO_MINUTOS="tt_position_ejercicio_minutos"
        const val TT_POSITION_EJERCICIO_SEGUNDOS="tt_position_ejercicio_segundos"
        const val TT_POSITION_PREPARACION_HORAS="tt_position_preparacion_horas"
        const val TT_POSITION_PREPARACION_MINUTOS="tt_position_preparacion_minutos"
        const val TT_POSITION_PREPARACION_SEGUNDOS="tt_position_preparacion_segundos"
        const val TT_POSITION_TRACK_DESCANSO="tt_position_track_descanso"
        const val TT_POSITION_TRACK_DESCANSO_ENTRE="tt_position_track_descanso_entre"
        const val TT_POSITION_TRACK_EJERCICIO="tt_position_track_ejercicio"


        const val CICLOS="ciclos"
        const val CONJUNTOS="conjuntos"
        const val TIEMPO_TOTAL="tiempo_total"

        const val RESULTADOS_IMC="resultados_imc"
    }
}